server.port: 9966 
spring.profiles: default
spring.jpa.show-sql : true
spring.jpa.generate-ddl: true
spring.jpa.hibernate.temp.use_jdbc_metadata_defaults: false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true
spring.jpa.properties.hibernate.temp.lob.use_jdbc_metadata_defaults: false 
spring.jpa.hibernate.ddl-auto: update
spring.jpa.database-platform: org.hibernate.dialect.PostgreSQL9Dialect 
spring.servlet.multipart.file-size-threshold: 2KB
spring.servlet.multipart.max-file-size: 200MB
spring.servlet.multipart.max-request-size: 215MB  
server.contextPath: /eis
spring.jpa.properties.hibernate.default_schema: eis
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres